name: tweakr-pipeline
services:
  - name: pipeline
    image: tweakr-pipeline
    ports:
      - port: 8080
        protocol: http
    env:
      - key: MONGODB_ATLAS_CLUSTER_URI
        value: {{ .MONGODB_ATLAS_CLUSTER_URI }}
      - key: MONGO_DB_NAME
        value: {{ .MONGO_DB_NAME }}
      - key: GOOGLE_GEMINI_KEY
        value: {{ .GOOGLE_GEMINI_KEY }}
    resources:
      instance_type: nano
    scaling:
      min: 1
      max: 1
    health_checks:
      http:
        path: /health
        port: 8080
        interval: 30s
        timeout: 5s
        unhealthy_threshold: 3
        healthy_threshold: 2 