"""updated the papers models

Revision ID: 0ba555b5dfbe
Revises: d3d83fc1bc9e
Create Date: 2024-12-03 12:39:36.231888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba555b5dfbe'
down_revision: Union[str, None] = 'd3d83fc1bc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
