"""updated the papers models to add indexes

Revision ID: 0c1b3ad4c625
Revises: 0ffd8d43fece
Create Date: 2024-12-03 12:54:47.608632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1b3ad4c625'
down_revision: Union[str, None] = '0ffd8d43fece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pub_date', sa.Date(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_category'), 'papers', ['category'], unique=False)
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_index(op.f('ix_papers_is_processed'), 'papers', ['is_processed'], unique=False)
    op.create_index(op.f('ix_papers_keywords'), 'papers', ['keywords'], unique=False)
    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_title'), table_name='papers')
    op.drop_index(op.f('ix_papers_keywords'), table_name='papers')
    op.drop_index(op.f('ix_papers_is_processed'), table_name='papers')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_category'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
