"""updated the papers models to add indexes

Revision ID: 0ffd8d43fece
Revises: 0ba555b5dfbe
Create Date: 2024-12-03 12:42:25.495457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffd8d43fece'
down_revision: Union[str, None] = '0ba555b5dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
