"""turn_json_array

Revision ID: 23f3b704f512
Revises: 639776eed1bf
Create Date: 2025-04-21 13:20:09.748545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23f3b704f512'
down_revision: Union[str, None] = '639776eed1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE subscription_plans 
        ALTER COLUMN features TYPE VARCHAR[] 
        USING CASE 
            WHEN features IS NULL THEN NULL 
            ELSE string_to_array(regexp_replace(features::text, '^\[|\]$', '', 'g'), ',')
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE subscription_plans 
        ALTER COLUMN features TYPE JSONB 
        USING CASE 
            WHEN features IS NULL THEN NULL 
            ELSE to_jsonb(features)
        END
    """)
    # ### end Alembic commands ###
