"""FEAT: added the url to the models

Revision ID: c55183dc24b2
Revises: c2cc7c5caa74
Create Date: 2024-12-17 14:18:16.809671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55183dc24b2'
down_revision: Union[str, None] = 'c2cc7c5caa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'url')
    # ### end Alembic commands ###
