"""updated the papers models to add the collection name in which the paper is a part of in the vector db

Revision ID: f3658e98c0b8
Revises: 0c1b3ad4c625
Create Date: 2024-12-03 12:56:45.408796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3658e98c0b8'
down_revision: Union[str, None] = '0c1b3ad4c625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('collection_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_papers_collection_name'), 'papers', ['collection_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_collection_name'), table_name='papers')
    op.drop_column('papers', 'collection_name')
    # ### end Alembic commands ###
