# Base image for Python
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY app /app/app
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose any required port (if necessary)
EXPOSE 8501



# Set the entry point for the application
CMD ["python", "app/app.py"]
