from dotenv import load_dotenv
import os

load_dotenv()

REDIS_URL = os.getenv("REDIS_URL")
SQLALCHEMY_DATABASE_URL = os.getenv("SQLALCHEMY_DATABASE_URL")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
STABILITYAI_APIKEY = os.getenv("STABILITYAI_APIKEY")
EMAIL = os.getenv("EMAIL")
DOMAIN = os.getenv("DOMAIN")
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_MINUTES = 60
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GOOGLE_GEMINI_KEY = os.getenv("GOOGLE_GEMINI_KEY")
EXPIRATION = 300
MONGO_DB_URL = os.getenv("MONGO_DB_URL")
BREVO_KEY = os.getenv("BREVO_API_KEY")
